# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-saml
  description: This component is responsible for provisioning SAML metadata into AWS IAM as new SAML providers
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









